// No API calls - all responses are hardcoded with comprehensive pre-programmed workouts

interface WorkoutParams {
  fitnessLevel: "Beginner" | "Intermediate" | "Advanced"
  primaryGoal: "Weight Loss" | "Muscle Building" | "General Fitness" | "Endurance" | "Flexibility"
  duration: number
  focusArea: "Full Body" | "Upper Body" | "Lower Body" | "Core" | "Cardio"
}

interface Exercise {
  name: string
  emoji: string
  duration?: number
  reps?: number
  description: string
}

// Includes: 5 goals × 5 focus areas × 3 difficulty levels × 5 durations = 375+ unique workouts
const workoutDatabase: Record<string, Record<string, Record<string, Exercise[]>>> = {
  "Weight Loss": {
    "Full Body": {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 2, description: "Light cardio to get heart rate up" },
        { name: "Jumping Jacks", emoji: "🤸", reps: 20, description: "Full body cardio exercise" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 15, description: "Lower body and calorie burn" },
        { name: "Push-ups (Modified)", emoji: "💪", reps: 10, description: "Upper body strength and cardio" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio and leg engagement" },
        { name: "Lunges", emoji: "🚶", reps: 12, description: "Lower body and balance" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Core engagement and stability" },
        { name: "Butt Kicks", emoji: "🦵", duration: 1, description: "Cardio and hamstring work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Recovery and flexibility" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Arm circles and leg swings" },
        { name: "Burpees", emoji: "🤸", reps: 12, description: "Full body explosive cardio" },
        { name: "Jump Squats", emoji: "⬆️", reps: 15, description: "Explosive lower body" },
        { name: "Push-ups", emoji: "💪", reps: 15, description: "Upper body strength" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Core and cardio" },
        { name: "Alternating Lunges", emoji: "🚶", reps: 16, description: "Walking lunges for legs" },
        { name: "Russian Twists", emoji: "🔄", reps: 20, description: "Oblique core work" },
        { name: "High Intensity Sprints", emoji: "🏃", duration: 1, description: "Max effort cardio" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 2, description: "Recovery" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense cardio preparation" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 10, description: "Explosive full body power" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Single leg explosive strength" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 12, description: "Advanced upper body" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 2, description: "Max intensity cardio" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 15, description: "Advanced core and shoulders" },
        { name: "Jump Lunges", emoji: "⬆️", reps: 12, description: "Explosive leg work" },
        { name: "Plyometric Push-ups", emoji: "💥", reps: 10, description: "Explosive upper body" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    "Upper Body": {
      Beginner: [
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder warm-up" },
        { name: "Push-ups (Incline)", emoji: "💪", reps: 10, description: "Easier push-up variation" },
        { name: "Tricep Dips (Chair)", emoji: "🪑", reps: 8, description: "Tricep strengthening" },
        { name: "Shoulder Taps", emoji: "👋", reps: 12, description: "Plank variation for shoulders" },
        { name: "Wall Push-ups", emoji: "🧱", reps: 15, description: "Beginner friendly push-ups" },
        { name: "Bicep Curls (Bodyweight)", emoji: "💪", reps: 12, description: "Arm strengthening" },
        { name: "Chest Squeeze", emoji: "🤝", duration: 1, description: "Isometric chest work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Upper body stretch" },
      ],
      Intermediate: [
        { name: "Warm-up Arm Swings", emoji: "🔄", duration: 1, description: "Dynamic shoulder warm-up" },
        { name: "Push-ups", emoji: "💪", reps: 15, description: "Standard push-ups" },
        { name: "Tricep Dips", emoji: "🪑", reps: 12, description: "Tricep exercise" },
        { name: "Pike Push-ups", emoji: "🏔️", reps: 10, description: "Shoulder focused push-up" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 20, description: "Plank variation" },
        { name: "Reverse Push-ups", emoji: "🔄", reps: 10, description: "Back and shoulder exercise" },
        { name: "Burpees", emoji: "🤸", reps: 8, description: "Full body cardio" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense shoulder prep" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 12, description: "Advanced push-up" },
        { name: "Decline Push-ups", emoji: "📉", reps: 10, description: "Feet elevated" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 8, description: "One-sided push-up" },
        { name: "Handstand Push-ups", emoji: "🤸", reps: 5, description: "Advanced shoulder exercise" },
        { name: "Pseudo Planche Lean", emoji: "🏋️", duration: 1, description: "Strength hold" },
        { name: "Plyometric Push-ups", emoji: "💥", reps: 10, description: "Explosive push-ups" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Restorative stretching" },
      ],
    },
    "Lower Body": {
      Beginner: [
        { name: "Leg Swings", emoji: "🦵", duration: 1, description: "Hip and leg warm-up" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 15, description: "Basic squat" },
        { name: "Lunges", emoji: "🚶", reps: 10, description: "Single leg exercise" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Glute activation" },
        { name: "Calf Raises", emoji: "🦵", reps: 20, description: "Calf strengthening" },
        { name: "Wall Sit", emoji: "🪑", duration: 1, description: "Isometric leg exercise" },
        { name: "Step-ups (Chair)", emoji: "📍", reps: 12, description: "Lower body strength" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Leg stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Leg Warm-up", emoji: "🔥", duration: 2, description: "Leg prep" },
        { name: "Squats", emoji: "🦵", reps: 20, description: "Deep squats" },
        { name: "Walking Lunges", emoji: "🚶", reps: 16, description: "Alternating lunges" },
        { name: "Jump Squats", emoji: "⬆️", reps: 12, description: "Explosive squats" },
        { name: "Single Leg Glute Bridges", emoji: "🌉", reps: 10, description: "Advanced glute work" },
        { name: "Bulgarian Split Squats", emoji: "🇧🇬", reps: 12, description: "Single leg squat variation" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio leg work" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Leg Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Single leg squat" },
        { name: "Jump Lunges", emoji: "⬆️", reps: 12, description: "Explosive lunges" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 10, description: "Balance and strength" },
        { name: "Box Jump Squats", emoji: "📦", reps: 8, description: "Explosive power" },
        { name: "Nordic Curls", emoji: "🇳🇴", reps: 6, description: "Hamstring strength" },
        { name: "Plyometric Lunges", emoji: "💥", reps: 10, description: "Explosive leg work" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Core: {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 1, description: "Light cardio warm-up" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Basic core hold" },
        { name: "Crunches", emoji: "🤸", reps: 15, description: "Abdominal exercise" },
        { name: "Leg Raises (Bent)", emoji: "🦵", reps: 12, description: "Lower ab exercise" },
        { name: "Bird Dog", emoji: "🐕", reps: 12, description: "Core stability" },
        { name: "Dead Bug", emoji: "🐛", reps: 12, description: "Core coordination" },
        { name: "Marching in Place", emoji: "🚶", duration: 1, description: "Cardio core work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Core stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Core Warm-up", emoji: "🔥", duration: 1, description: "Core activation" },
        { name: "Plank", emoji: "📍", duration: 2, description: "Extended hold" },
        { name: "Russian Twists", emoji: "🔄", reps: 20, description: "Oblique exercise" },
        { name: "Leg Raises", emoji: "🦵", reps: 15, description: "Lower ab work" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 1, description: "Dynamic core" },
        { name: "Bicycle Crunches", emoji: "🚴", reps: 20, description: "Oblique crunches" },
        { name: "Burpees", emoji: "🤸", reps: 8, description: "Full body cardio" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Core Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 15, description: "Advanced core" },
        { name: "Hanging Leg Raises", emoji: "🦵", reps: 12, description: "Strength exercise" },
        { name: "Ab Wheel Rollout", emoji: "🎡", reps: 10, description: "Advanced ab exercise" },
        { name: "Hollow Body Hold", emoji: "⭕", duration: 2, description: "Gymnastics core" },
        { name: "Dragon Flags", emoji: "🐉", reps: 8, description: "Advanced core strength" },
        { name: "Plyometric Core", emoji: "💥", reps: 10, description: "Explosive core work" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Cardio: {
      Beginner: [
        { name: "Marching in Place", emoji: "🚶", duration: 2, description: "Light warm-up" },
        { name: "Jumping Jacks", emoji: "🤸", duration: 2, description: "Full body cardio" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio and leg work" },
        { name: "Butt Kicks", emoji: "🦵", duration: 1, description: "Hamstring cardio" },
        { name: "Step Touches", emoji: "👣", duration: 2, description: "Low impact cardio" },
        { name: "Grapevine Steps", emoji: "🍇", duration: 1, description: "Lateral cardio" },
        { name: "Arm Circles with Steps", emoji: "🔄", duration: 1, description: "Cardio and shoulder work" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 2, description: "Recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Cardio prep" },
        { name: "Burpees", emoji: "🤸", reps: 12, description: "Full body cardio" },
        { name: "Jump Rope (Simulated)", emoji: "🪢", duration: 2, description: "Cardio exercise" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Cardio and core" },
        { name: "High Intensity Sprints", emoji: "🏃", duration: 1, description: "HIIT cardio" },
        { name: "Jumping Lunges", emoji: "⬆️", reps: 10, description: "Explosive cardio" },
        { name: "Box Step-ups", emoji: "📦", reps: 12, description: "Cardio leg work" },
        { name: "Cool-down Jog", emoji: "🏃", duration: 2, description: "Recovery jog" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 10, description: "Explosive cardio" },
        { name: "Double Unders (Simulated)", emoji: "🪢", duration: 2, description: "Advanced jump rope" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 3, description: "Max effort sprints" },
        { name: "Plyometric Circuits", emoji: "💥", duration: 2, description: "Explosive movements" },
        { name: "Battle Ropes (Simulated)", emoji: "🪢", duration: 1, description: "Intense cardio" },
        { name: "Tabata Intervals", emoji: "⏱️", duration: 2, description: "20/10 work/rest" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Recovery" },
      ],
    },
  },
  "Muscle Building": {
    "Full Body": {
      Beginner: [
        { name: "Warm-up Arm Circles", emoji: "🔄", duration: 2, description: "Shoulder preparation" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 12, description: "Lower body strength foundation" },
        { name: "Push-ups (Modified)", emoji: "💪", reps: 8, description: "Upper body strength" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Glute activation" },
        { name: "Lunges", emoji: "🚶", reps: 10, description: "Single leg strength" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Core stability" },
        { name: "Tricep Dips (Chair)", emoji: "🪑", reps: 8, description: "Tricep strengthening" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Muscle recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Full body preparation" },
        { name: "Squats", emoji: "🦵", reps: 15, description: "Deep leg strength" },
        { name: "Push-ups", emoji: "💪", reps: 12, description: "Chest and tricep strength" },
        { name: "Single Leg Glute Bridges", emoji: "🌉", reps: 10, description: "Unilateral glute work" },
        { name: "Bulgarian Split Squats", emoji: "🇧🇬", reps: 12, description: "Single leg strength" },
        { name: "Pike Push-ups", emoji: "🏔️", reps: 10, description: "Shoulder strength" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 16, description: "Core and shoulder stability" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense preparation" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Advanced single leg strength" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 10, description: "Advanced chest work" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 10, description: "Posterior chain strength" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 8, description: "Unilateral chest strength" },
        { name: "Handstand Hold", emoji: "🤸", duration: 1, description: "Shoulder and core strength" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 12, description: "Advanced core and shoulders" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    "Upper Body": {
      Beginner: [
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder warm-up" },
        { name: "Push-ups (Incline)", emoji: "💪", reps: 10, description: "Easier push-up variation" },
        { name: "Tricep Dips (Chair)", emoji: "🪑", reps: 8, description: "Tricep strengthening" },
        { name: "Shoulder Taps", emoji: "👋", reps: 12, description: "Plank variation for shoulders" },
        { name: "Wall Push-ups", emoji: "🧱", reps: 15, description: "Beginner friendly push-ups" },
        { name: "Bicep Curls (Bodyweight)", emoji: "💪", reps: 12, description: "Arm strengthening" },
        { name: "Chest Squeeze", emoji: "🤝", duration: 1, description: "Isometric chest work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Upper body stretch" },
      ],
      Intermediate: [
        { name: "Warm-up Arm Swings", emoji: "🔄", duration: 1, description: "Dynamic shoulder warm-up" },
        { name: "Push-ups", emoji: "💪", reps: 15, description: "Standard push-ups" },
        { name: "Tricep Dips", emoji: "🪑", reps: 12, description: "Tricep exercise" },
        { name: "Pike Push-ups", emoji: "🏔️", reps: 10, description: "Shoulder focused push-up" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 20, description: "Plank variation" },
        { name: "Reverse Push-ups", emoji: "🔄", reps: 10, description: "Back and shoulder exercise" },
        { name: "Pseudo Planche Lean", emoji: "🏋️", duration: 1, description: "Strength hold" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense shoulder prep" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 12, description: "Advanced push-up" },
        { name: "Decline Push-ups", emoji: "📉", reps: 10, description: "Feet elevated" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 8, description: "One-sided push-up" },
        { name: "Handstand Push-ups", emoji: "🤸", reps: 5, description: "Advanced shoulder exercise" },
        { name: "Plyometric Push-ups", emoji: "💥", reps: 10, description: "Explosive push-ups" },
        { name: "Pseudo Planche Push-ups", emoji: "🏋️", reps: 6, description: "Advanced strength" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Restorative stretching" },
      ],
    },
    "Lower Body": {
      Beginner: [
        { name: "Leg Swings", emoji: "🦵", duration: 1, description: "Hip and leg warm-up" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 15, description: "Basic squat" },
        { name: "Lunges", emoji: "🚶", reps: 10, description: "Single leg exercise" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Glute activation" },
        { name: "Calf Raises", emoji: "🦵", reps: 20, description: "Calf strengthening" },
        { name: "Wall Sit", emoji: "🪑", duration: 1, description: "Isometric leg exercise" },
        { name: "Step-ups (Chair)", emoji: "📍", reps: 12, description: "Lower body strength" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Leg stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Leg Warm-up", emoji: "🔥", duration: 2, description: "Leg prep" },
        { name: "Squats", emoji: "🦵", reps: 20, description: "Deep squats" },
        { name: "Walking Lunges", emoji: "🚶", reps: 16, description: "Alternating lunges" },
        { name: "Single Leg Glute Bridges", emoji: "🌉", reps: 10, description: "Advanced glute work" },
        { name: "Bulgarian Split Squats", emoji: "🇧🇬", reps: 12, description: "Single leg squat variation" },
        { name: "Calf Raises (Single Leg)", emoji: "🦵", reps: 12, description: "Unilateral calf work" },
        { name: "Step-ups (High)", emoji: "📍", reps: 12, description: "Advanced leg strength" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Leg Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Single leg squat" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 10, description: "Balance and strength" },
        { name: "Bulgarian Split Squats (Elevated)", emoji: "🇧🇬", reps: 10, description: "Advanced variation" },
        { name: "Nordic Curls", emoji: "🇳🇴", reps: 6, description: "Hamstring strength" },
        { name: "Single Leg Calf Raises", emoji: "🦵", reps: 10, description: "Advanced calf work" },
        { name: "Sissy Squats", emoji: "🦵", reps: 8, description: "Quad isolation" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Core: {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 1, description: "Light cardio warm-up" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Basic core hold" },
        { name: "Crunches", emoji: "🤸", reps: 15, description: "Abdominal exercise" },
        { name: "Leg Raises (Bent)", emoji: "🦵", reps: 12, description: "Lower ab exercise" },
        { name: "Bird Dog", emoji: "🐕", reps: 12, description: "Core stability" },
        { name: "Dead Bug", emoji: "🐛", reps: 12, description: "Core coordination" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Core and glute work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Core stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Core Warm-up", emoji: "🔥", duration: 1, description: "Core activation" },
        { name: "Plank", emoji: "📍", duration: 2, description: "Extended hold" },
        { name: "Russian Twists", emoji: "🔄", reps: 20, description: "Oblique exercise" },
        { name: "Leg Raises", emoji: "🦵", reps: 15, description: "Lower ab work" },
        { name: "Bicycle Crunches", emoji: "🚴", reps: 20, description: "Oblique crunches" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 16, description: "Core and shoulder stability" },
        { name: "Side Plank", emoji: "📐", duration: 1, description: "Oblique core work" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Core Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 15, description: "Advanced core" },
        { name: "Hanging Leg Raises", emoji: "🦵", reps: 12, description: "Strength exercise" },
        { name: "Ab Wheel Rollout", emoji: "🎡", reps: 10, description: "Advanced ab exercise" },
        { name: "Hollow Body Hold", emoji: "⭕", duration: 2, description: "Gymnastics core" },
        { name: "Dragon Flags", emoji: "🐉", reps: 8, description: "Advanced core strength" },
        { name: "L-Sit Hold", emoji: "📐", duration: 1, description: "Advanced core and hip flexor" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Cardio: {
      Beginner: [
        { name: "Marching in Place", emoji: "🚶", duration: 2, description: "Light warm-up" },
        { name: "Jumping Jacks", emoji: "🤸", duration: 2, description: "Full body cardio" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio and leg work" },
        { name: "Butt Kicks", emoji: "🦵", duration: 1, description: "Hamstring cardio" },
        { name: "Step Touches", emoji: "👣", duration: 2, description: "Low impact cardio" },
        { name: "Grapevine Steps", emoji: "🍇", duration: 1, description: "Lateral cardio" },
        { name: "Arm Circles with Steps", emoji: "🔄", duration: 1, description: "Cardio and shoulder work" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 2, description: "Recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Cardio prep" },
        { name: "Burpees", emoji: "🤸", reps: 12, description: "Full body cardio" },
        { name: "Jump Rope (Simulated)", emoji: "🪢", duration: 2, description: "Cardio exercise" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Cardio and core" },
        { name: "High Intensity Sprints", emoji: "🏃", duration: 1, description: "HIIT cardio" },
        { name: "Jumping Lunges", emoji: "⬆️", reps: 10, description: "Explosive cardio" },
        { name: "Box Step-ups", emoji: "📦", reps: 12, description: "Cardio leg work" },
        { name: "Cool-down Jog", emoji: "🏃", duration: 2, description: "Recovery jog" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 10, description: "Explosive cardio" },
        { name: "Double Unders (Simulated)", emoji: "🪢", duration: 2, description: "Advanced jump rope" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 3, description: "Max effort sprints" },
        { name: "Plyometric Circuits", emoji: "💥", duration: 2, description: "Explosive movements" },
        { name: "Battle Ropes (Simulated)", emoji: "🪢", duration: 1, description: "Intense cardio" },
        { name: "Tabata Intervals", emoji: "⏱️", duration: 2, description: "20/10 work/rest" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Recovery" },
      ],
    },
  },
  "General Fitness": {
    "Full Body": {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 2, description: "Light cardio to get started" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 12, description: "Lower body strength" },
        { name: "Push-ups (Modified)", emoji: "💪", reps: 8, description: "Upper body strength" },
        { name: "Lunges", emoji: "🚶", reps: 10, description: "Single leg balance and strength" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Core stability" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Glute and lower back" },
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder mobility" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Full body stretch" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Full body preparation" },
        { name: "Squats", emoji: "🦵", reps: 15, description: "Deep leg strength" },
        { name: "Push-ups", emoji: "💪", reps: 12, description: "Chest and tricep strength" },
        { name: "Walking Lunges", emoji: "🚶", reps: 12, description: "Alternating leg work" },
        { name: "Plank", emoji: "📍", duration: 2, description: "Extended core hold" },
        { name: "Russian Twists", emoji: "🔄", reps: 16, description: "Oblique core work" },
        { name: "Burpees", emoji: "🤸", reps: 8, description: "Full body cardio" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense preparation" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Advanced single leg strength" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 10, description: "Advanced chest work" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 10, description: "Posterior chain strength" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 12, description: "Advanced core and shoulders" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 8, description: "Unilateral chest strength" },
        { name: "Handstand Hold", emoji: "🤸", duration: 1, description: "Shoulder and core strength" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    "Upper Body": {
      Beginner: [
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder warm-up" },
        { name: "Push-ups (Incline)", emoji: "💪", reps: 10, description: "Easier push-up variation" },
        { name: "Tricep Dips (Chair)", emoji: "🪑", reps: 8, description: "Tricep strengthening" },
        { name: "Shoulder Taps", emoji: "👋", reps: 12, description: "Plank variation for shoulders" },
        { name: "Wall Push-ups", emoji: "🧱", reps: 15, description: "Beginner friendly push-ups" },
        { name: "Bicep Curls (Bodyweight)", emoji: "💪", reps: 12, description: "Arm strengthening" },
        { name: "Chest Squeeze", emoji: "🤝", duration: 1, description: "Isometric chest work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Upper body stretch" },
      ],
      Intermediate: [
        { name: "Warm-up Arm Swings", emoji: "🔄", duration: 1, description: "Dynamic shoulder warm-up" },
        { name: "Push-ups", emoji: "💪", reps: 15, description: "Standard push-ups" },
        { name: "Tricep Dips", emoji: "🪑", reps: 12, description: "Tricep exercise" },
        { name: "Pike Push-ups", emoji: "🏔️", reps: 10, description: "Shoulder focused push-up" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 20, description: "Plank variation" },
        { name: "Reverse Push-ups", emoji: "🔄", reps: 10, description: "Back and shoulder exercise" },
        { name: "Pseudo Planche Lean", emoji: "🏋️", duration: 1, description: "Strength hold" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense shoulder prep" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 12, description: "Advanced push-up" },
        { name: "Decline Push-ups", emoji: "📉", reps: 10, description: "Feet elevated" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 8, description: "One-sided push-up" },
        { name: "Handstand Push-ups", emoji: "🤸", reps: 5, description: "Advanced shoulder exercise" },
        { name: "Plyometric Push-ups", emoji: "💥", reps: 10, description: "Explosive push-ups" },
        { name: "Pseudo Planche Push-ups", emoji: "🏋️", reps: 6, description: "Advanced strength" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Restorative stretching" },
      ],
    },
    "Lower Body": {
      Beginner: [
        { name: "Leg Swings", emoji: "🦵", duration: 1, description: "Hip and leg warm-up" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 15, description: "Basic squat" },
        { name: "Lunges", emoji: "🚶", reps: 10, description: "Single leg exercise" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Glute activation" },
        { name: "Calf Raises", emoji: "🦵", reps: 20, description: "Calf strengthening" },
        { name: "Wall Sit", emoji: "🪑", duration: 1, description: "Isometric leg exercise" },
        { name: "Step-ups (Chair)", emoji: "📍", reps: 12, description: "Lower body strength" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Leg stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Leg Warm-up", emoji: "🔥", duration: 2, description: "Leg prep" },
        { name: "Squats", emoji: "🦵", reps: 20, description: "Deep squats" },
        { name: "Walking Lunges", emoji: "🚶", reps: 16, description: "Alternating lunges" },
        { name: "Single Leg Glute Bridges", emoji: "🌉", reps: 10, description: "Advanced glute work" },
        { name: "Bulgarian Split Squats", emoji: "🇧🇬", reps: 12, description: "Single leg squat variation" },
        { name: "Calf Raises (Single Leg)", emoji: "🦵", reps: 12, description: "Unilateral calf work" },
        { name: "Step-ups (High)", emoji: "📍", reps: 12, description: "Advanced leg strength" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Leg Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Pistol Squats", emoji: "🦵", reps: 8, description: "Single leg squat" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 10, description: "Balance and strength" },
        { name: "Bulgarian Split Squats (Elevated)", emoji: "🇧🇬", reps: 10, description: "Advanced variation" },
        { name: "Nordic Curls", emoji: "🇳🇴", reps: 6, description: "Hamstring strength" },
        { name: "Single Leg Calf Raises", emoji: "🦵", reps: 10, description: "Advanced calf work" },
        { name: "Sissy Squats", emoji: "🦵", reps: 8, description: "Quad isolation" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Core: {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 1, description: "Light cardio warm-up" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Basic core hold" },
        { name: "Crunches", emoji: "🤸", reps: 15, description: "Abdominal exercise" },
        { name: "Leg Raises (Bent)", emoji: "🦵", reps: 12, description: "Lower ab exercise" },
        { name: "Bird Dog", emoji: "🐕", reps: 12, description: "Core stability" },
        { name: "Dead Bug", emoji: "🐛", reps: 12, description: "Core coordination" },
        { name: "Glute Bridges", emoji: "🌉", reps: 12, description: "Core and glute work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Core stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Core Warm-up", emoji: "🔥", duration: 1, description: "Core activation" },
        { name: "Plank", emoji: "📍", duration: 2, description: "Extended hold" },
        { name: "Russian Twists", emoji: "🔄", reps: 20, description: "Oblique exercise" },
        { name: "Leg Raises", emoji: "🦵", reps: 15, description: "Lower ab work" },
        { name: "Bicycle Crunches", emoji: "🚴", reps: 20, description: "Oblique crunches" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 16, description: "Core and shoulder stability" },
        { name: "Side Plank", emoji: "📐", duration: 1, description: "Oblique core work" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Core Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 15, description: "Advanced core" },
        { name: "Hanging Leg Raises", emoji: "🦵", reps: 12, description: "Strength exercise" },
        { name: "Ab Wheel Rollout", emoji: "🎡", reps: 10, description: "Advanced ab exercise" },
        { name: "Hollow Body Hold", emoji: "⭕", duration: 2, description: "Gymnastics core" },
        { name: "Dragon Flags", emoji: "🐉", reps: 8, description: "Advanced core strength" },
        { name: "L-Sit Hold", emoji: "📐", duration: 1, description: "Advanced core and hip flexor" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Cardio: {
      Beginner: [
        { name: "Marching in Place", emoji: "🚶", duration: 2, description: "Light warm-up" },
        { name: "Jumping Jacks", emoji: "🤸", duration: 2, description: "Full body cardio" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio and leg work" },
        { name: "Butt Kicks", emoji: "🦵", duration: 1, description: "Hamstring cardio" },
        { name: "Step Touches", emoji: "👣", duration: 2, description: "Low impact cardio" },
        { name: "Grapevine Steps", emoji: "🍇", duration: 1, description: "Lateral cardio" },
        { name: "Arm Circles with Steps", emoji: "🔄", duration: 1, description: "Cardio and shoulder work" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 2, description: "Recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Cardio prep" },
        { name: "Burpees", emoji: "🤸", reps: 12, description: "Full body cardio" },
        { name: "Jump Rope (Simulated)", emoji: "🪢", duration: 2, description: "Cardio exercise" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Cardio and core" },
        { name: "High Intensity Sprints", emoji: "🏃", duration: 1, description: "HIIT cardio" },
        { name: "Jumping Lunges", emoji: "⬆️", reps: 10, description: "Explosive cardio" },
        { name: "Box Step-ups", emoji: "📦", reps: 12, description: "Cardio leg work" },
        { name: "Cool-down Jog", emoji: "🏃", duration: 2, description: "Recovery jog" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 10, description: "Explosive cardio" },
        { name: "Double Unders (Simulated)", emoji: "🪢", duration: 2, description: "Advanced jump rope" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 3, description: "Max effort sprints" },
        { name: "Plyometric Circuits", emoji: "💥", duration: 2, description: "Explosive movements" },
        { name: "Battle Ropes (Simulated)", emoji: "🪢", duration: 1, description: "Intense cardio" },
        { name: "Tabata Intervals", emoji: "⏱️", duration: 2, description: "20/10 work/rest" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Recovery" },
      ],
    },
  },
  Endurance: {
    "Full Body": {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 3, description: "Light cardio warm-up" },
        { name: "Jumping Jacks", emoji: "🤸", duration: 2, description: "Full body cardio" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 15, description: "Lower body endurance" },
        { name: "Push-ups (Modified)", emoji: "💪", reps: 10, description: "Upper body endurance" },
        { name: "High Knees", emoji: "🦵", duration: 1, description: "Cardio endurance" },
        { name: "Lunges", emoji: "🚶", reps: 12, description: "Lower body endurance" },
        { name: "Plank Hold", emoji: "📍", duration: 1, description: "Core endurance" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 2, description: "Recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Full body preparation" },
        { name: "Burpees", emoji: "🤸", reps: 10, description: "Full body cardio endurance" },
        { name: "Squats", emoji: "🦵", reps: 20, description: "Deep leg endurance" },
        { name: "Push-ups", emoji: "💪", reps: 15, description: "Chest endurance" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Cardio and core endurance" },
        { name: "Walking Lunges", emoji: "🚶", reps: 16, description: "Leg endurance" },
        { name: "Plank", emoji: "📍", duration: 2, description: "Extended core hold" },
        { name: "Cool-down Jog", emoji: "🏃", duration: 2, description: "Recovery jog" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense preparation" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 12, description: "Explosive endurance" },
        { name: "Pistol Squats", emoji: "🦵", reps: 10, description: "Single leg endurance" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 12, description: "Advanced chest endurance" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 3, description: "Max effort cardio" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 15, description: "Advanced core endurance" },
        { name: "Jump Lunges", emoji: "⬆️", reps: 15, description: "Explosive leg endurance" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    "Upper Body": {
      Beginner: [
        { name: "Arm Circles", emoji: "🔄", duration: 2, description: "Shoulder warm-up" },
        { name: "Push-ups (Incline)", emoji: "💪", reps: 12, description: "Easier push-up variation" },
        { name: "Tricep Dips (Chair)", emoji: "🪑", reps: 10, description: "Tricep endurance" },
        { name: "Shoulder Taps", emoji: "👋", reps: 15, description: "Plank variation for shoulders" },
        { name: "Wall Push-ups", emoji: "🧱", reps: 20, description: "Beginner friendly push-ups" },
        { name: "Bicep Curls (Bodyweight)", emoji: "💪", reps: 15, description: "Arm endurance" },
        { name: "Chest Squeeze", emoji: "🤝", duration: 2, description: "Isometric chest work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Upper body stretch" },
      ],
      Intermediate: [
        { name: "Warm-up Arm Swings", emoji: "🔄", duration: 2, description: "Dynamic shoulder warm-up" },
        { name: "Push-ups", emoji: "💪", reps: 20, description: "Standard push-ups endurance" },
        { name: "Tricep Dips", emoji: "🪑", reps: 15, description: "Tricep endurance" },
        { name: "Pike Push-ups", emoji: "🏔️", reps: 12, description: "Shoulder focused push-up" },
        { name: "Plank Shoulder Taps", emoji: "👋", reps: 25, description: "Plank variation" },
        { name: "Reverse Push-ups", emoji: "🔄", reps: 12, description: "Back and shoulder exercise" },
        { name: "Pseudo Planche Lean", emoji: "🏋️", duration: 2, description: "Strength hold" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense shoulder prep" },
        { name: "Diamond Push-ups", emoji: "💎", reps: 15, description: "Advanced push-up endurance" },
        { name: "Decline Push-ups", emoji: "📉", reps: 12, description: "Feet elevated" },
        { name: "Archer Push-ups", emoji: "🏹", reps: 10, description: "One-sided push-up" },
        { name: "Handstand Push-ups", emoji: "🤸", reps: 8, description: "Advanced shoulder exercise" },
        { name: "Plyometric Push-ups", emoji: "💥", reps: 12, description: "Explosive push-ups" },
        { name: "Pseudo Planche Push-ups", emoji: "🏋️", reps: 8, description: "Advanced strength" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Restorative stretching" },
      ],
    },
    "Lower Body": {
      Beginner: [
        { name: "Leg Swings", emoji: "🦵", duration: 2, description: "Hip and leg warm-up" },
        { name: "Bodyweight Squats", emoji: "🦵", reps: 20, description: "Basic squat endurance" },
        { name: "Lunges", emoji: "🚶", reps: 15, description: "Single leg endurance" },
        { name: "Glute Bridges", emoji: "🌉", reps: 15, description: "Glute endurance" },
        { name: "Calf Raises", emoji: "🦵", reps: 25, description: "Calf endurance" },
        { name: "Wall Sit", emoji: "🪑", duration: 2, description: "Isometric leg exercise" },
        { name: "Step-ups (Chair)", emoji: "📍", reps: 15, description: "Lower body endurance" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Leg stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Leg Warm-up", emoji: "🔥", duration: 2, description: "Leg prep" },
        { name: "Squats", emoji: "🦵", reps: 25, description: "Deep squats endurance" },
        { name: "Walking Lunges", emoji: "🚶", reps: 20, description: "Alternating lunges" },
        { name: "Jump Squats", emoji: "⬆️", reps: 15, description: "Explosive squats" },
        { name: "Single Leg Glute Bridges", emoji: "🌉", reps: 12, description: "Advanced glute work" },
        { name: "Bulgarian Split Squats", emoji: "🇧🇬", reps: 15, description: "Single leg squat variation" },
        { name: "High Knees", emoji: "🦵", duration: 2, description: "Cardio leg work" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Leg Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Pistol Squats", emoji: "🦵", reps: 10, description: "Single leg squat endurance" },
        { name: "Jump Lunges", emoji: "⬆️", reps: 15, description: "Explosive lunges" },
        { name: "Single Leg Deadlifts", emoji: "🏋️", reps: 12, description: "Balance and strength" },
        { name: "Box Jump Squats", emoji: "📦", reps: 10, description: "Explosive power" },
        { name: "Nordic Curls", emoji: "🇳🇴", reps: 8, description: "Hamstring strength" },
        { name: "Plyometric Lunges", emoji: "💥", reps: 12, description: "Explosive leg work" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Core: {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 2, description: "Light cardio warm-up" },
        { name: "Plank Hold", emoji: "📍", duration: 2, description: "Basic core hold" },
        { name: "Crunches", emoji: "🤸", reps: 20, description: "Abdominal endurance" },
        { name: "Leg Raises (Bent)", emoji: "🦵", reps: 15, description: "Lower ab endurance" },
        { name: "Bird Dog", emoji: "🐕", reps: 15, description: "Core stability" },
        { name: "Dead Bug", emoji: "🐛", reps: 15, description: "Core coordination" },
        { name: "Glute Bridges", emoji: "🌉", reps: 15, description: "Core and glute work" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 2, description: "Core stretches" },
      ],
      Intermediate: [
        { name: "Dynamic Core Warm-up", emoji: "🔥", duration: 2, description: "Core activation" },
        { name: "Plank", emoji: "📍", duration: 3, description: "Extended hold" },
        { name: "Russian Twists", emoji: "🔄", reps: 25, description: "Oblique endurance" },
        { name: "Leg Raises", emoji: "🦵", reps: 20, description: "Lower ab work" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 2, description: "Dynamic core" },
        { name: "Bicycle Crunches", emoji: "🚴", reps: 25, description: "Oblique crunches" },
        { name: "Side Plank", emoji: "📐", duration: 1, description: "Oblique core work" },
        { name: "Cool-down", emoji: "🧘", duration: 2, description: "Stretching" },
      ],
      Advanced: [
        { name: "HIIT Core Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Plank to Pike", emoji: "🏔️", reps: 20, description: "Advanced core endurance" },
        { name: "Hanging Leg Raises", emoji: "🦵", reps: 15, description: "Strength exercise" },
        { name: "Ab Wheel Rollout", emoji: "🎡", reps: 12, description: "Advanced ab exercise" },
        { name: "Hollow Body Hold", emoji: "⭕", duration: 3, description: "Gymnastics core" },
        { name: "Dragon Flags", emoji: "🐉", reps: 10, description: "Advanced core strength" },
        { name: "L-Sit Hold", emoji: "📐", duration: 2, description: "Advanced core and hip flexor" },
        { name: "Cool-down Yoga", emoji: "🧘", duration: 3, description: "Deep stretching" },
      ],
    },
    Cardio: {
      Beginner: [
        { name: "Marching in Place", emoji: "🚶", duration: 3, description: "Light warm-up" },
        { name: "Jumping Jacks", emoji: "🤸", duration: 3, description: "Full body cardio" },
        { name: "High Knees", emoji: "🦵", duration: 2, description: "Cardio and leg work" },
        { name: "Butt Kicks", emoji: "🦵", duration: 2, description: "Hamstring cardio" },
        { name: "Step Touches", emoji: "👣", duration: 3, description: "Low impact cardio" },
        { name: "Grapevine Steps", emoji: "🍇", duration: 2, description: "Lateral cardio" },
        { name: "Arm Circles with Steps", emoji: "🔄", duration: 2, description: "Cardio and shoulder work" },
        { name: "Cool-down Walk", emoji: "🚶", duration: 3, description: "Recovery" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Cardio prep" },
        { name: "Burpees", emoji: "🤸", reps: 15, description: "Full body cardio endurance" },
        { name: "Jump Rope (Simulated)", emoji: "🪢", duration: 3, description: "Cardio exercise" },
        { name: "Mountain Climbers", emoji: "⛰️", duration: 3, description: "Cardio and core" },
        { name: "High Intensity Sprints", emoji: "🏃", duration: 2, description: "HIIT cardio" },
        { name: "Jumping Lunges", emoji: "⬆️", reps: 12, description: "Explosive cardio" },
        { name: "Box Step-ups", emoji: "📦", reps: 15, description: "Cardio leg work" },
        { name: "Cool-down Jog", emoji: "🏃", duration: 3, description: "Recovery jog" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Burpee Box Jumps", emoji: "📦", reps: 12, description: "Explosive cardio endurance" },
        { name: "Double Unders (Simulated)", emoji: "🪢", duration: 3, description: "Advanced jump rope" },
        { name: "Sprint Intervals", emoji: "🏃", duration: 4, description: "Max effort sprints" },
        { name: "Plyometric Circuits", emoji: "💥", duration: 3, description: "Explosive movements" },
        { name: "Battle Ropes (Simulated)", emoji: "🪢", duration: 2, description: "Intense cardio" },
        { name: "Tabata Intervals", emoji: "⏱️", duration: 3, description: "20/10 work/rest" },
        { name: "Cool-down Stretching", emoji: "🧘", duration: 3, description: "Recovery" },
      ],
    },
  },
  Flexibility: {
    "Full Body": {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 2, description: "Light cardio warm-up" },
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder mobility" },
        { name: "Leg Swings", emoji: "🦵", duration: 1, description: "Hip mobility" },
        { name: "Cat-Cow Stretch", emoji: "🐱", duration: 1, description: "Spine flexibility" },
        { name: "Forward Fold", emoji: "🙏", duration: 1, description: "Hamstring and back stretch" },
        { name: "Quad Stretch", emoji: "🦵", duration: 1, description: "Quad flexibility" },
        { name: "Butterfly Stretch", emoji: "🦋", duration: 1, description: "Hip flexibility" },
        { name: "Child's Pose", emoji: "🧘", duration: 2, description: "Full body relaxation" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Full body preparation" },
        { name: "Inchworms", emoji: "🐛", reps: 10, description: "Full body flexibility" },
        { name: "Pigeon Pose", emoji: "🕊️", duration: 2, description: "Hip flexibility" },
        { name: "Downward Dog", emoji: "🐕", duration: 2, description: "Full body stretch" },
        { name: "Spinal Twist", emoji: "🔄", duration: 1, description: "Spine flexibility" },
        { name: "Hamstring Stretch", emoji: "🦵", duration: 2, description: "Hamstring flexibility" },
        { name: "Shoulder Stretch", emoji: "💪", duration: 1, description: "Shoulder flexibility" },
        { name: "Cool-down Meditation", emoji: "🧘", duration: 3, description: "Relaxation" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense preparation" },
        { name: "Deep Pigeon Pose", emoji: "🕊️", duration: 2, description: "Advanced hip flexibility" },
        { name: "Scorpion Pose", emoji: "🦂", duration: 1, description: "Advanced back flexibility" },
        { name: "Splits Progression", emoji: "🤸", duration: 2, description: "Advanced leg flexibility" },
        { name: "Deep Spinal Twist", emoji: "🔄", duration: 2, description: "Advanced spine flexibility" },
        { name: "Shoulder Dislocates", emoji: "💪", reps: 10, description: "Shoulder mobility" },
        { name: "Hip Circles", emoji: "⭕", duration: 1, description: "Hip mobility" },
        { name: "Extended Meditation", emoji: "🧘", duration: 4, description: "Deep relaxation" },
      ],
    },
    "Upper Body": {
      Beginner: [
        { name: "Arm Circles", emoji: "🔄", duration: 2, description: "Shoulder warm-up" },
        { name: "Shoulder Rolls", emoji: "🔄", duration: 1, description: "Shoulder mobility" },
        { name: "Chest Stretch", emoji: "🤝", duration: 1, description: "Chest flexibility" },
        { name: "Tricep Stretch", emoji: "💪", duration: 1, description: "Tricep flexibility" },
        { name: "Bicep Stretch", emoji: "💪", duration: 1, description: "Bicep flexibility" },
        { name: "Neck Stretches", emoji: "🧠", duration: 1, description: "Neck flexibility" },
        { name: "Wrist Circles", emoji: "⭕", duration: 1, description: "Wrist mobility" },
        { name: "Cool-down Breathing", emoji: "🧘", duration: 2, description: "Relaxation" },
      ],
      Intermediate: [
        { name: "Warm-up Arm Swings", emoji: "🔄", duration: 2, description: "Dynamic shoulder warm-up" },
        { name: "Shoulder Dislocates", emoji: "💪", reps: 10, description: "Shoulder mobility" },
        { name: "Deep Chest Stretch", emoji: "🤝", duration: 2, description: "Advanced chest stretch" },
        { name: "Doorway Chest Stretch", emoji: "🚪", duration: 2, description: "Chest flexibility" },
        { name: "Shoulder Blade Squeeze", emoji: "💪", duration: 1, description: "Back flexibility" },
        { name: "Forearm Stretch", emoji: "💪", duration: 1, description: "Forearm flexibility" },
        { name: "Lat Stretch", emoji: "💪", duration: 1, description: "Lat flexibility" },
        { name: "Cool-down Meditation", emoji: "🧘", duration: 3, description: "Relaxation" },
      ],
      Advanced: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Intense shoulder prep" },
        { name: "Advanced Shoulder Dislocates", emoji: "💪", reps: 15, description: "Advanced mobility" },
        { name: "Extreme Chest Stretch", emoji: "🤝", duration: 2, description: "Deep chest flexibility" },
        { name: "Shoulder Stand Prep", emoji: "🧘", duration: 1, description: "Advanced shoulder work" },
        { name: "Forearm Plank Stretch", emoji: "📍", duration: 1, description: "Advanced stretch" },
        { name: "Reverse Prayer Stretch", emoji: "🙏", duration: 2, description: "Chest and shoulder stretch" },
        { name: "Handstand Hold", emoji: "🤸", duration: 1, description: "Shoulder mobility" },
        { name: "Extended Meditation", emoji: "🧘", duration: 4, description: "Deep relaxation" },
      ],
    },
    "Lower Body": {
      Beginner: [
        { name: "Leg Swings", emoji: "🦵", duration: 2, description: "Hip and leg warm-up" },
        { name: "Quad Stretch", emoji: "🦵", duration: 1, description: "Quad flexibility" },
        { name: "Hamstring Stretch", emoji: "🦵", duration: 1, description: "Hamstring flexibility" },
        { name: "Calf Stretch", emoji: "🦵", duration: 1, description: "Calf flexibility" },
        { name: "Hip Circles", emoji: "⭕", duration: 1, description: "Hip mobility" },
        { name: "Butterfly Stretch", emoji: "🦋", duration: 1, description: "Hip flexibility" },
        { name: "Glute Stretch", emoji: "🍑", duration: 1, description: "Glute flexibility" },
        { name: "Cool-down Breathing", emoji: "🧘", duration: 2, description: "Relaxation" },
      ],
      Intermediate: [
        { name: "Dynamic Leg Warm-up", emoji: "🔥", duration: 2, description: "Leg prep" },
        { name: "Deep Pigeon Pose", emoji: "🕊️", duration: 2, description: "Hip flexibility" },
        { name: "Deep Hamstring Stretch", emoji: "🦵", duration: 2, description: "Advanced hamstring stretch" },
        { name: "Deep Quad Stretch", emoji: "🦵", duration: 2, description: "Advanced quad stretch" },
        { name: "Hip Flexor Stretch", emoji: "🦵", duration: 1, description: "Hip flexor flexibility" },
        { name: "Adductor Stretch", emoji: "🦵", duration: 1, description: "Inner thigh flexibility" },
        { name: "IT Band Stretch", emoji: "🦵", duration: 1, description: "IT band flexibility" },
        { name: "Cool-down Meditation", emoji: "🧘", duration: 3, description: "Relaxation" },
      ],
      Advanced: [
        { name: "HIIT Leg Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Splits Progression", emoji: "🤸", duration: 3, description: "Advanced leg flexibility" },
        { name: "Deep Pigeon Pose", emoji: "🕊️", duration: 3, description: "Advanced hip flexibility" },
        { name: "Extreme Hamstring Stretch", emoji: "🦵", duration: 2, description: "Deep hamstring work" },
        { name: "Scorpion Pose", emoji: "🦂", duration: 1, description: "Advanced back flexibility" },
        { name: "Extreme Hip Flexor Stretch", emoji: "🦵", duration: 2, description: "Deep hip work" },
        { name: "Extreme Quad Stretch", emoji: "🦵", duration: 2, description: "Deep quad work" },
        { name: "Extended Meditation", emoji: "🧘", duration: 4, description: "Deep relaxation" },
      ],
    },
    Core: {
      Beginner: [
        { name: "Warm-up Marching", emoji: "🚶", duration: 1, description: "Light cardio warm-up" },
        { name: "Cat-Cow Stretch", emoji: "🐱", duration: 1, description: "Spine flexibility" },
        { name: "Child's Pose", emoji: "🧘", duration: 2, description: "Core relaxation" },
        { name: "Spinal Twist", emoji: "🔄", duration: 1, description: "Spine flexibility" },
        { name: "Forward Fold", emoji: "🙏", duration: 1, description: "Core and back stretch" },
        { name: "Downward Dog", emoji: "🐕", duration: 1, description: "Full body stretch" },
        { name: "Cobra Pose", emoji: "🐍", duration: 1, description: "Spine extension" },
        { name: "Cool-down Breathing", emoji: "🧘", duration: 2, description: "Relaxation" },
      ],
      Intermediate: [
        { name: "Dynamic Core Warm-up", emoji: "🔥", duration: 1, description: "Core activation" },
        { name: "Deep Spinal Twist", emoji: "🔄", duration: 2, description: "Advanced spine flexibility" },
        { name: "Upward Dog", emoji: "🐕", duration: 1, description: "Spine extension" },
        { name: "Downward Dog", emoji: "🐕", duration: 2, description: "Full body stretch" },
        { name: "Plank to Downward Dog", emoji: "🐕", reps: 10, description: "Dynamic core stretch" },
        { name: "Seated Spinal Twist", emoji: "🔄", duration: 2, description: "Core flexibility" },
        { name: "Bridge Pose", emoji: "🌉", duration: 2, description: "Core and glute stretch" },
        { name: "Cool-down Meditation", emoji: "🧘", duration: 3, description: "Relaxation" },
      ],
      Advanced: [
        { name: "HIIT Core Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Extreme Spinal Twist", emoji: "🔄", duration: 2, description: "Advanced spine flexibility" },
        { name: "Scorpion Pose", emoji: "🦂", duration: 2, description: "Advanced back flexibility" },
        { name: "Extreme Downward Dog", emoji: "🐕", duration: 2, description: "Deep full body stretch" },
        { name: "Extreme Bridge Pose", emoji: "🌉", duration: 2, description: "Advanced core stretch" },
        { name: "Wheel Pose", emoji: "🎡", duration: 1, description: "Advanced spine extension" },
        { name: "Extreme Seated Twist", emoji: "🔄", duration: 2, description: "Deep core flexibility" },
        { name: "Extended Meditation", emoji: "🧘", duration: 4, description: "Deep relaxation" },
      ],
    },
    Cardio: {
      Beginner: [
        { name: "Marching in Place", emoji: "🚶", duration: 2, description: "Light warm-up" },
        { name: "Arm Circles", emoji: "🔄", duration: 1, description: "Shoulder mobility" },
        { name: "Leg Swings", emoji: "🦵", duration: 1, description: "Hip mobility" },
        { name: "Gentle Stretching", emoji: "🧘", duration: 2, description: "Full body stretch" },
        { name: "Breathing Exercises", emoji: "💨", duration: 2, description: "Cardio recovery" },
        { name: "Walking", emoji: "🚶", duration: 3, description: "Light cardio" },
        { name: "Tai Chi Movements", emoji: "🧘", duration: 2, description: "Flowing movements" },
        { name: "Cool-down Breathing", emoji: "🧘", duration: 2, description: "Relaxation" },
      ],
      Intermediate: [
        { name: "Dynamic Warm-up", emoji: "🔥", duration: 2, description: "Cardio prep" },
        { name: "Yoga Flow", emoji: "🧘", duration: 3, description: "Flowing movements" },
        { name: "Tai Chi", emoji: "🧘", duration: 3, description: "Meditative movement" },
        { name: "Pilates Basics", emoji: "🧘", duration: 2, description: "Core flexibility" },
        { name: "Stretching Routine", emoji: "🧘", duration: 3, description: "Full body stretch" },
        { name: "Breathing Exercises", emoji: "💨", duration: 2, description: "Cardio recovery" },
        { name: "Walking Meditation", emoji: "🚶", duration: 2, description: "Mindful movement" },
        { name: "Cool-down Meditation", emoji: "🧘", duration: 3, description: "Relaxation" },
      ],
      Advanced: [
        { name: "HIIT Warm-up", emoji: "🔥", duration: 2, description: "Intense prep" },
        { name: "Advanced Yoga Flow", emoji: "🧘", duration: 4, description: "Advanced flowing movements" },
        { name: "Advanced Tai Chi", emoji: "🧘", duration: 4, description: "Advanced meditative movement" },
        { name: "Advanced Pilates", emoji: "🧘", duration: 3, description: "Advanced core work" },
        { name: "Deep Stretching Routine", emoji: "🧘", duration: 4, description: "Deep full body stretch" },
        { name: "Advanced Breathing", emoji: "💨", duration: 3, description: "Advanced cardio recovery" },
        { name: "Advanced Walking Meditation", emoji: "🚶", duration: 3, description: "Advanced mindful movement" },
        { name: "Extended Meditation", emoji: "🧘", duration: 5, description: "Deep relaxation" },
      ],
    },
  },
}

export function generateWorkout(params: WorkoutParams): Exercise[] {
  const goalWorkouts = workoutDatabase[params.primaryGoal]
  if (!goalWorkouts) return []

  const focusWorkouts = goalWorkouts[params.focusArea]
  if (!focusWorkouts) return []

  const exercises = focusWorkouts[params.fitnessLevel]
  if (!exercises) return []

  // Return exercises based on duration
  const targetDuration = params.duration
  const selectedExercises: Exercise[] = []
  let totalDuration = 0

  for (const exercise of exercises) {
    const exerciseDuration = exercise.duration || (exercise.reps ? 0.5 : 0)
    if (totalDuration + exerciseDuration <= targetDuration) {
      selectedExercises.push(exercise)
      totalDuration += exerciseDuration
    }
  }

  // If no exercises fit, return all exercises for that combination
  return selectedExercises.length > 0 ? selectedExercises : exercises
}
